# Delly build script

language: cpp

sudo: false

matrix:
  include:
    - env: MYCC="gcc-4.8" MYCXX="g++-4.8"
      os: linux
      addons: &gcc48
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8

    - env: MYCC="gcc-5" MYCXX="g++-5"
      os: linux
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

    - env: MYCC="gcc-6" MYCXX="g++-6"
      os: linux
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz; fi

before_script:
  - export CXX=$MYCXX
  - export CC=$MYCC
  - $CXX --version

script:
  - make all
